# Generated by Django 4.0.2 on 2023-05-21 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fahp', '0002_siswa_rapor_bahasa_siswa_h_siswa_rapor_ipa_siswa_h_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='derajat_probabilitas',
            new_name='serajat_probabilitas',
        ),
    ]
