# Generated by Django 4.0.2 on 2023-05-21 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fahp', '0003_rename_derajat_probabilitas_serajat_probabilitas'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='serajat_probabilitas',
            new_name='derajat_probabilitas',
        ),
    ]
