# Generated by Django 4.0.2 on 2023-05-28 03:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fahp', '0004_rename_serajat_probabilitas_derajat_probabilitas'),
    ]

    operations = [
        migrations.AddField(
            model_name='sub_kriteria',
            name='id_kriteria',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='fahp.kriteria'),
        ),
    ]
