# Generated by Django 4.0.2 on 2023-05-28 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fahp', '0005_sub_kriteria_id_kriteria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sub_kriteria',
            name='id_subKriteria',
            field=models.CharField(max_length=3, primary_key=True, serialize=False),
        ),
    ]
