# Generated by Django 4.0.2 on 2023-05-28 04:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fahp', '0007_rename_id_kriteria_sub_kriteria_kriteria'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hasil',
            old_name='id_subKriteria',
            new_name='id_subkriteria',
        ),
        migrations.RenameField(
            model_name='sub_kriteria',
            old_name='bobot_hasil_subKriteria',
            new_name='bobot_hasil_subkriteria',
        ),
        migrations.RenameField(
            model_name='sub_kriteria',
            old_name='bobot_subKriteria',
            new_name='bobot_subkriteria',
        ),
        migrations.RenameField(
            model_name='sub_kriteria',
            old_name='id_subKriteria',
            new_name='id_subkriteria',
        ),
        migrations.RenameField(
            model_name='sub_kriteria',
            old_name='nama_subKriteria',
            new_name='nama_subkriteria',
        ),
    ]
