# Generated by Django 4.0.2 on 2023-05-28 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fahp', '0008_rename_id_subkriteria_hasil_id_subkriteria_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kriteria',
            name='bobot_hasil_kriteria',
        ),
        migrations.RemoveField(
            model_name='kriteria',
            name='bobot_kriteria',
        ),
    ]
