# Generated by Django 4.0.2 on 2023-05-28 11:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fahp', '0009_remove_kriteria_bobot_hasil_kriteria_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sub_kriteria',
            name='bobot_hasil_subkriteria',
        ),
        migrations.RemoveField(
            model_name='sub_kriteria',
            name='bobot_subkriteria',
        ),
        migrations.CreateModel(
            name='bobot_kriteria_ahp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nilai', models.FloatField()),
                ('kriteria', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='fahp.kriteria')),
                ('subkriteria', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='fahp.sub_kriteria')),
            ],
        ),
    ]
