# Generated by Django 4.0.2 on 2023-05-28 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fahp', '0010_remove_sub_kriteria_bobot_hasil_subkriteria_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bobot_kriteria_ahp',
            old_name='kriteria',
            new_name='kriteria1',
        ),
        migrations.RemoveField(
            model_name='bobot_kriteria_ahp',
            name='subkriteria',
        ),
        migrations.AddField(
            model_name='bobot_kriteria_ahp',
            name='kriteria2',
            field=models.CharField(max_length=2, null=True),
        ),
    ]
