# Generated by Django 4.0.2 on 2023-05-28 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fahp', '0011_rename_kriteria_bobot_kriteria_ahp_kriteria1_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bobot_kriteria_ahp',
            old_name='nilai',
            new_name='bobotk1',
        ),
        migrations.AddField(
            model_name='bobot_kriteria_ahp',
            name='bobotk2',
            field=models.FloatField(null=True),
        ),
    ]
