# Generated by Django 4.0.2 on 2023-05-28 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fahp', '0012_rename_nilai_bobot_kriteria_ahp_bobotk1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bobot_kriteria_ahp',
            name='id',
            field=models.CharField(max_length=4, primary_key=True, serialize=False),
        ),
    ]
