# Generated by Django 4.0.2 on 2023-05-28 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fahp', '0013_alter_bobot_kriteria_ahp_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='bobot_kriteria_ahp',
            name='bobot_normal',
            field=models.FloatField(null=True),
        ),
    ]
