# Generated by Django 4.0.2 on 2023-05-29 11:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fahp', '0014_bobot_kriteria_ahp_bobot_normal'),
    ]

    operations = [
        migrations.CreateModel(
            name='sum_kriteria_ahp',
            fields=[
                ('id', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('sum_ahp', models.FloatField()),
                ('kriteria', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='fahp.kriteria')),
            ],
        ),
    ]
