# Generated by Django 4.0.2 on 2023-05-29 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fahp', '0016_bobot_kriteria_ahp_normalisasi'),
    ]

    operations = [
        migrations.AddField(
            model_name='sum_kriteria_ahp',
            name='bobot_ahp',
            field=models.FloatField(null=True),
        ),
    ]
