# Generated by Django 4.0.2 on 2023-05-29 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fahp', '0017_sum_kriteria_ahp_bobot_ahp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bobot_kriteria_ahp',
            old_name='normalisasi',
            new_name='nilai_norm',
        ),
    ]
