# Generated by Django 4.0.2 on 2023-05-29 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fahp', '0018_rename_normalisasi_bobot_kriteria_ahp_nilai_norm'),
    ]

    operations = [
        migrations.AddField(
            model_name='bobot_kriteria_ahp',
            name='nilai_konsistensi',
            field=models.FloatField(null=True),
        ),
    ]
