# Generated by Django 4.0.2 on 2023-05-30 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fahp', '0019_bobot_kriteria_ahp_nilai_konsistensi'),
    ]

    operations = [
        migrations.AddField(
            model_name='sum_kriteria_ahp',
            name='sum_kosistensi',
            field=models.FloatField(null=True),
        ),
    ]
