# Generated by Django 4.0.2 on 2023-05-30 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fahp', '0020_sum_kriteria_ahp_sum_kosistensi'),
    ]

    operations = [
        migrations.AddField(
            model_name='sum_kriteria_ahp',
            name='sum_kosistensi2',
            field=models.FloatField(null=True),
        ),
    ]
