# Generated by Django 4.0.2 on 2023-05-31 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fahp', '0022_skala_fuzzy'),
    ]

    operations = [
        migrations.CreateModel(
            name='skala_fuzzy2',
            fields=[
                ('id', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('l', models.FloatField()),
                ('m', models.FloatField(null=True)),
                ('u', models.FloatField(null=True)),
            ],
        ),
    ]
