# Generated by Django 4.0.2 on 2023-06-01 00:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fahp', '0023_skala_fuzzy2'),
    ]

    operations = [
        migrations.CreateModel(
            name='bobot_kriteria_fahp',
            fields=[
                ('id', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('kriteria2', models.CharField(max_length=2, null=True)),
                ('jumlah_l', models.FloatField(null=True)),
                ('jumlah_m', models.FloatField(null=True)),
                ('jumlah_u', models.FloatField(null=True)),
                ('si_l', models.FloatField(null=True)),
                ('si_m', models.FloatField(null=True)),
                ('si_u', models.FloatField(null=True)),
                ('bobotk1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='fahp.skala_fuzzy')),
                ('bobotk2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='fahp.skala_fuzzy2')),
                ('kriteria1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='fahp.kriteria')),
            ],
        ),
    ]
