# Generated by Django 4.0.2 on 2023-06-01 02:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fahp', '0024_bobot_kriteria_fahp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bobot_kriteria_fahp',
            name='jumlah_l',
        ),
        migrations.RemoveField(
            model_name='bobot_kriteria_fahp',
            name='jumlah_m',
        ),
        migrations.RemoveField(
            model_name='bobot_kriteria_fahp',
            name='jumlah_u',
        ),
        migrations.RemoveField(
            model_name='bobot_kriteria_fahp',
            name='si_l',
        ),
        migrations.RemoveField(
            model_name='bobot_kriteria_fahp',
            name='si_m',
        ),
        migrations.RemoveField(
            model_name='bobot_kriteria_fahp',
            name='si_u',
        ),
        migrations.AlterField(
            model_name='skala_fuzzy',
            name='id',
            field=models.CharField(max_length=1, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='skala_fuzzy2',
            name='id',
            field=models.CharField(max_length=1, primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='sum_kriteria_fahp',
            fields=[
                ('id', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('sum_ahp', models.FloatField()),
                ('bobot_ahp', models.FloatField(null=True)),
                ('sum_kosistensi', models.FloatField(null=True)),
                ('sum_kosistensi2', models.FloatField(null=True)),
                ('kriteria', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='fahp.kriteria')),
            ],
        ),
    ]
