# Generated by Django 4.0.2 on 2023-06-02 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fahp', '0026_rename_bobot_ahp_sum_kriteria_fahp_jumlah_l_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='derajat_probabilitas',
        ),
        migrations.RenameField(
            model_name='hasil',
            old_name='id_kriteria',
            new_name='kriteria',
        ),
    ]
