# Generated by Django 4.0.2 on 2023-06-02 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fahp', '0028_derajat_probabilitas'),
    ]

    operations = [
        migrations.RenameField(
            model_name='derajat_probabilitas',
            old_name='kriteria1',
            new_name='kriteria',
        ),
    ]
