# Generated by Django 4.0.2 on 2023-06-02 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fahp', '0029_rename_kriteria1_derajat_probabilitas_kriteria'),
    ]

    operations = [
        migrations.AddField(
            model_name='derajat_probabilitas',
            name='kriteria1',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='derajat_probabilitas',
            name='kriteria2',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
