# Generated by Django 4.0.2 on 2023-06-02 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fahp', '0030_derajat_probabilitas_kriteria1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='kriteria',
            name='bobot_kriteria',
            field=models.FloatField(null=True),
        ),
    ]
