# Generated by Django 4.0.2 on 2023-06-04 02:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fahp', '0031_kriteria_bobot_kriteria'),
    ]

    operations = [
        migrations.CreateModel(
            name='bobot_subkriteria_ahp',
            fields=[
                ('id', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('subkriteria2', models.CharField(max_length=3, null=True)),
                ('bobotk1', models.FloatField()),
                ('bobotk2', models.FloatField(null=True)),
                ('bobot_normal', models.FloatField(null=True)),
                ('nilai_norm', models.FloatField(null=True)),
                ('nilai_konsistensi', models.FloatField(null=True)),
                ('subkriteria1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='fahp.sub_kriteria')),
            ],
        ),
    ]
