# Generated by Django 4.0.2 on 2023-06-04 14:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fahp', '0032_bobot_subkriteria_ahp'),
    ]

    operations = [
        migrations.CreateModel(
            name='sum_subkriteria_ahp',
            fields=[
                ('id', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('sum_ahp', models.FloatField()),
                ('bobot_ahp', models.FloatField(null=True)),
                ('sum_kosistensi', models.FloatField(null=True)),
                ('sum_kosistensi2', models.FloatField(null=True)),
                ('subkriteria', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='fahp.sub_kriteria')),
            ],
        ),
        migrations.CreateModel(
            name='bobot_subkriteria_fahp',
            fields=[
                ('id', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('subkriteria2', models.CharField(max_length=2, null=True)),
                ('bobotk1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='fahp.skala_fuzzy')),
                ('bobotk2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='fahp.skala_fuzzy2')),
                ('subkriteria1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='fahp.sub_kriteria')),
            ],
        ),
    ]
