# Generated by Django 4.0.2 on 2023-06-04 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fahp', '0035_alter_bobot_subkriteria_fahp_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sum_subkriteria_ahp',
            name='id',
            field=models.CharField(max_length=4, primary_key=True, serialize=False),
        ),
    ]
