# Generated by Django 4.0.2 on 2023-06-05 13:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fahp', '0041_bobot_subkriteria_fahp_kriteria_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sum_kriteria_fahp',
            name='id',
            field=models.CharField(max_length=6, primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='sum_subkriteria_fahp',
            fields=[
                ('id', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('jumlah_l', models.FloatField(null=True)),
                ('jumlah_m', models.FloatField(null=True)),
                ('jumlah_u', models.FloatField(null=True)),
                ('si_l', models.FloatField(null=True)),
                ('si_m', models.FloatField(null=True)),
                ('si_u', models.FloatField(null=True)),
                ('kriteria', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='fahp.kriteria')),
                ('subkriteria', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='fahp.sub_kriteria')),
            ],
        ),
        migrations.CreateModel(
            name='derajat_probabilitas_sub',
            fields=[
                ('id', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('nilai', models.FloatField(null=True)),
                ('kriteria1', models.CharField(max_length=20, null=True)),
                ('kriteria2', models.CharField(max_length=20, null=True)),
                ('kriteria', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='fahp.kriteria')),
                ('subkriteria', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='fahp.sub_kriteria')),
            ],
        ),
    ]
