# Generated by Django 4.0.2 on 2023-06-05 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fahp', '0043_rename_kriteria1_derajat_probabilitas_sub_subkriteria1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sub_kriteria',
            name='bobot_subkriteria',
            field=models.FloatField(null=True),
        ),
    ]
