# Generated by Django 4.0.2 on 2023-06-08 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fahp', '0046_rename_id_subkriteria_hasil_subkriteria'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hasil',
            old_name='id_siswa',
            new_name='siswa',
        ),
    ]
