# Generated by Django 4.0.2 on 2023-06-08 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fahp', '0047_rename_id_siswa_hasil_siswa'),
    ]

    operations = [
        migrations.AddField(
            model_name='hasil',
            name='nilai',
            field=models.FloatField(null=True),
        ),
    ]
