# Generated by Django 4.0.2 on 2023-06-08 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fahp', '0048_hasil_nilai'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hasil',
            name='id',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
    ]
