# Generated by Django 4.0.2 on 2023-06-14 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fahp', '0050_rename_nilai_hasil_nilai_kriteria_hasil_nilai_sub'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siswa',
            name='iq_siswa',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='siswa',
            name='rapor_bahasa_siswa',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='siswa',
            name='rapor_ipa_siswa',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='siswa',
            name='rapor_ips_siswa',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='siswa',
            name='tpa_bahasa_siswa',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='siswa',
            name='tpa_ipa_siswa',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='siswa',
            name='tpa_ips_siswa',
            field=models.FloatField(),
        ),
    ]
