# Generated by Django 4.0.2 on 2023-06-15 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fahp', '0052_laporan_hasil_laporan_hasil_d'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laporan_hasil_d',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
