# Generated by Django 4.0.2 on 2023-06-15 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fahp', '0053_alter_laporan_hasil_d_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='laporan_hasil_d',
        ),
    ]
