# Generated by Django 4.0.2 on 2023-07-09 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fahp', '0056_alter_laporan_hasil_d_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='laporan_hasil_d',
            name='kriteria',
        ),
    ]
