# Generated by Django 4.0.2 on 2023-07-09 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fahp', '0058_hasil_dummy'),
    ]

    operations = [
        migrations.DeleteModel(
            name='hasil_dummy',
        ),
    ]
