# Generated by Django 4.0.2 on 2023-07-09 10:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fahp', '0059_delete_hasil_dummy'),
    ]

    operations = [
        migrations.CreateModel(
            name='hasil_dummy',
            fields=[
                ('id_dummy', models.AutoField(primary_key=True, serialize=False)),
                ('nilai_sub1', models.FloatField()),
                ('nilai_sub2', models.FloatField()),
                ('nilai_sub3', models.FloatField()),
                ('siswa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fahp.siswa')),
            ],
        ),
    ]
