# Generated by Django 4.0.2 on 2023-07-09 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fahp', '0061_hasil_dummy1'),
    ]

    operations = [
        migrations.DeleteModel(
            name='hasil_dummy1',
        ),
    ]
