# Generated by Django 4.0.2 on 2023-07-09 10:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fahp', '0062_delete_hasil_dummy1'),
    ]

    operations = [
        migrations.CreateModel(
            name='hasil_dummy1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nilai_sub1', models.FloatField()),
                ('nilai_sub2', models.FloatField()),
                ('nilai_sub3', models.FloatField()),
                ('siswa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fahp.siswa')),
            ],
        ),
    ]
