# Generated by Django 4.0.2 on 2023-07-11 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fahp', '0063_hasil_dummy1'),
    ]

    operations = [
        migrations.AddField(
            model_name='laporan_hasil',
            name='tanggal',
            field=models.DateField(null=True),
        ),
    ]
