# Generated by Django 4.0.2 on 2023-07-11 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fahp', '0064_laporan_hasil_tanggal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laporan_hasil',
            name='tanggal',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
